openapi: 3.0.0

info:
  title: Health Hub Content Optimization Backend
  version: 0.0.1

servers:
  - url: http://localhost:8000
    description: Local server hosted on the default port.


components:
  schemas:



    Group:
      type: object
      properties:
        id:
          type: string
          example: "E2A0b0e274cDdF591C9Bb5bbFD33C479"
        name:
          type: string
          example: "Group 7365"
        pending_articles:
          type: array
          items:
            $ref: '#/components/schemas/Article'
        remove_articles:
          type: array
          items:
            $ref: '#/components/schemas/NotYetImplemented'
        ignore_articles:
          type: array
          items:
            $ref: '#/components/schemas/NotYetImplemented'
        optimise_articles:
          type: array
          items:
            $ref: '#/components/schemas/NotYetImplemented'
        combine_articles:
          type: array
          items:
            $ref: '#/components/schemas/NotYetImplemented'

    Article:
      type: object
      properties:
        id:
          type: string
          example: "E2A0b0e274cDdF591C9Bb5bbFD33C479"
        title:
          type: string
          example: "Article Title"
        description:
          type: string
          example: "Lorem ipsum dolor sit amet..."
        pr_name:
          type: string
          example: "Author Name"
        content_category:
          type: string
          example: "Health and Wellness"
        url:
          type: string
          example: "www.url-to-resource.com"
        labels:
          type: array
          items:
            type: string
          example: ["Label A", "Label B"]
        keywords:
          type: array
          items:
            type: string
          example: [ "Keyword A", "Keyword B" ]
        cover_image_url:
          type: string
          example: "www.content-resource.com"
        engagement_rate:
          type: number
          format: float
          example: 0.72
          description: "Engagement is within the bounds of [0,1]"
        number_of_views:
          type: integer
          example: 98764

    NotYetImplemented:
      type: object
      additionalProperties: true


paths:

  ### Check endpoints
  /check/health:
    get:
      summary: Checks if the server is running
      responses:
        '200':
          description: Server is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"

  ### Group endpoints
  /groups:
    get:
      summary: Fetches all groups in the database
      responses:
        '200':
          description: Successfully fetched all groups
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'

  /groups/{group_id}:
      get:
        summary: Fetches a specific group by ID
        parameters:
          - name: group_id
            in: path
            required: true
            description: The ID of the group to retrieve
            schema:
              type: string
        responses:
          '200':
            description: Successfully fetched the cluster
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Group'
