# An example workflow configuration

# The name of your workflow
name: Publish and share Kedro Viz

permissions:
  # The contents write permission is required to use the action
  # if your GitHub publishing source is a branch
  contents: write

  # The pages and id-token write permissions are required to use
  # the action if your GitHub publishing source is a custom
  # GitHub Actions workflow
  pages: write
  id-token: write

on:
  # This can be configured based on your requirements
  # (i.e., the workflow trigger condition)
  pull_request:
    paths:
      - "**/pipelines.py"
      - "**/nodes.py"
  workflow_dispatch:

# We mentioned the minimal jobs for the workflow
jobs:
  deploy:
    # The action is currently tested on ubuntu-latest (Recommended)
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Requires python >= 3.9
          python-version: 3.12.3
        # This installs the Kedro-project dependencies
      - name: Install Project Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # This is not required if your Kedro Project
          # is at the root of your GitHub Repository
          cd content-optimization
        # Using the action
      - name: Deploy Kedro-Viz to GH Pages
        uses: kedro-org/publish-kedro-viz@v1
        with:
          # This is not required if your Kedro Project
          # is at the root of your GitHub Repository
          project_path: "content-optimization"
